package ict.ac.cn.hibernate;

// Generated 2014-8-24 12:59:22 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cpuinfo generated by hbm2java
 */
@Entity
@Table(name = "cpuinfo", catalog = "bdtune")
public class Cpuinfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7810433999825586055L;
	private Long cpuid;
	private String hostname;
	private Long nice;
	private Long sys;
	private Long idle;
	private Long iowait;
	private Long irq;
	private Long softirq;
	private Long intr;
	private Long ctx;
	private Long procs;
	private Long running;
	private Long blocked;
	private Long time;
	private Long usr;

	public Cpuinfo() {
	}

	public Cpuinfo(String hostname) {
		this.hostname = hostname;
	}

	public Cpuinfo(String hostname, Long nice, Long sys, Long idle,
			Long iowait, Long irq, Long softirq, Long intr, Long ctx,
			Long procs, Long running, Long blocked, Long time, Long usr) {
		this.hostname = hostname;
		this.nice = nice;
		this.sys = sys;
		this.idle = idle;
		this.iowait = iowait;
		this.irq = irq;
		this.softirq = softirq;
		this.intr = intr;
		this.ctx = ctx;
		this.procs = procs;
		this.running = running;
		this.blocked = blocked;
		this.time = time;
		this.usr = usr;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cpuid", unique = true, nullable = false)
	public Long getCpuid() {
		return this.cpuid;
	}

	public void setCpuid(Long cpuid) {
		this.cpuid = cpuid;
	}

	@Column(name = "hostname", nullable = false, length = 32)
	public String getHostname() {
		return this.hostname;
	}

	public void setHostname(String hostname) {
		this.hostname = hostname;
	}

	@Column(name = "nice")
	public Long getNice() {
		return this.nice;
	}

	public void setNice(Long nice) {
		this.nice = nice;
	}

	@Column(name = "sys")
	public Long getSys() {
		return this.sys;
	}

	public void setSys(Long sys) {
		this.sys = sys;
	}

	@Column(name = "idle")
	public Long getIdle() {
		return this.idle;
	}

	public void setIdle(Long idle) {
		this.idle = idle;
	}

	@Column(name = "iowait")
	public Long getIowait() {
		return this.iowait;
	}

	public void setIowait(Long iowait) {
		this.iowait = iowait;
	}

	@Column(name = "irq")
	public Long getIrq() {
		return this.irq;
	}

	public void setIrq(Long irq) {
		this.irq = irq;
	}

	@Column(name = "softirq")
	public Long getSoftirq() {
		return this.softirq;
	}

	public void setSoftirq(Long softirq) {
		this.softirq = softirq;
	}

	@Column(name = "intr")
	public Long getIntr() {
		return this.intr;
	}

	public void setIntr(Long intr) {
		this.intr = intr;
	}

	@Column(name = "ctx")
	public Long getCtx() {
		return this.ctx;
	}

	public void setCtx(Long ctx) {
		this.ctx = ctx;
	}

	@Column(name = "procs")
	public Long getProcs() {
		return this.procs;
	}

	public void setProcs(Long procs) {
		this.procs = procs;
	}

	@Column(name = "running")
	public Long getRunning() {
		return this.running;
	}

	public void setRunning(Long running) {
		this.running = running;
	}

	@Column(name = "blocked")
	public Long getBlocked() {
		return this.blocked;
	}

	public void setBlocked(Long blocked) {
		this.blocked = blocked;
	}

	@Column(name = "time")
	public Long getTime() {
		return this.time;
	}

	public void setTime(Long time) {
		this.time = time;
	}

	@Column(name = "usr")
	public Long getUsr() {
		return this.usr;
	}

	public void setUsr(Long usr) {
		this.usr = usr;
	}

}
