package ict.ac.cn.hibernate;

// Generated 2014-8-24 12:59:22 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Disk generated by hbm2java
 */
@Entity
@Table(name = "disk", catalog = "bdtune")
public class Disk implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3106445874502637641L;
	private Long diskid;
	private Long timestamp;
	private String hostname;
	private Long diskRead;
	private Long diskReadMerged;
	private Long diskReadSectors;
	private Long diskReadTime;
	private Long diskWrite;
	private Long diskWriteMerged;
	private Long diskWriteSectors;
	private Long diskWriteTime;
	private Long progressIo;
	private Long ioTime;
	private Long ioTimeWeighted;

	public Disk() {
	}

	public Disk(String hostname) {
		this.hostname = hostname;
	}

	public Disk(String hostname, Long diskRead, Long diskReadMerged,
			Long diskReadSectors, Long diskReadTime, Long diskWrite,
			Long diskWriteMerged, Long diskWriteSectors, Long diskWriteTime,
			Long progressIo, Long ioTime, Long ioTimeWeighted) {
		this.hostname = hostname;
		this.diskRead = diskRead;
		this.diskReadMerged = diskReadMerged;
		this.diskReadSectors = diskReadSectors;
		this.diskReadTime = diskReadTime;
		this.diskWrite = diskWrite;
		this.diskWriteMerged = diskWriteMerged;
		this.diskWriteSectors = diskWriteSectors;
		this.diskWriteTime = diskWriteTime;
		this.progressIo = progressIo;
		this.ioTime = ioTime;
		this.ioTimeWeighted = ioTimeWeighted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "diskid", unique = true, nullable = false)
	public Long getDiskid() {
		return this.diskid;
	}

	public void setDiskid(Long diskid) {
		this.diskid = diskid;
	}

	@Version
	@Column(name = "timestamp")
	public Long getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Long timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "hostname", nullable = false, length = 32)
	public String getHostname() {
		return this.hostname;
	}

	public void setHostname(String hostname) {
		this.hostname = hostname;
	}

	@Column(name = "disk_read")
	public Long getDiskRead() {
		return this.diskRead;
	}

	public void setDiskRead(Long diskRead) {
		this.diskRead = diskRead;
	}

	@Column(name = "disk_read_merged")
	public Long getDiskReadMerged() {
		return this.diskReadMerged;
	}

	public void setDiskReadMerged(Long diskReadMerged) {
		this.diskReadMerged = diskReadMerged;
	}

	@Column(name = "disk_read_sectors")
	public Long getDiskReadSectors() {
		return this.diskReadSectors;
	}

	public void setDiskReadSectors(Long diskReadSectors) {
		this.diskReadSectors = diskReadSectors;
	}

	@Column(name = "disk_read_time")
	public Long getDiskReadTime() {
		return this.diskReadTime;
	}

	public void setDiskReadTime(Long diskReadTime) {
		this.diskReadTime = diskReadTime;
	}

	@Column(name = "disk_write")
	public Long getDiskWrite() {
		return this.diskWrite;
	}

	public void setDiskWrite(Long diskWrite) {
		this.diskWrite = diskWrite;
	}

	@Column(name = "disk_write_merged")
	public Long getDiskWriteMerged() {
		return this.diskWriteMerged;
	}

	public void setDiskWriteMerged(Long diskWriteMerged) {
		this.diskWriteMerged = diskWriteMerged;
	}

	@Column(name = "disk_write_sectors")
	public Long getDiskWriteSectors() {
		return this.diskWriteSectors;
	}

	public void setDiskWriteSectors(Long diskWriteSectors) {
		this.diskWriteSectors = diskWriteSectors;
	}

	@Column(name = "disk_write_time")
	public Long getDiskWriteTime() {
		return this.diskWriteTime;
	}

	public void setDiskWriteTime(Long diskWriteTime) {
		this.diskWriteTime = diskWriteTime;
	}

	@Column(name = "progress_io")
	public Long getProgressIo() {
		return this.progressIo;
	}

	public void setProgressIo(Long progressIo) {
		this.progressIo = progressIo;
	}

	@Column(name = "io_time")
	public Long getIoTime() {
		return this.ioTime;
	}

	public void setIoTime(Long ioTime) {
		this.ioTime = ioTime;
	}

	@Column(name = "io_time_weighted")
	public Long getIoTimeWeighted() {
		return this.ioTimeWeighted;
	}

	public void setIoTimeWeighted(Long ioTimeWeighted) {
		this.ioTimeWeighted = ioTimeWeighted;
	}

}
