package ict.ac.cn.hibernate;

// Generated 2014-8-24 12:59:22 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Host generated by hbm2java
 */
@Entity
@Table(name = "host", catalog = "bdtune")
public class Host implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3632261045354424800L;
	private String hostname;
	private Long mapattempt;

	public Host() {
	}

	public Host(String hostname) {
		this.hostname = hostname;
	}

	public Host(String hostname, Long mapattempt) {
		this.hostname = hostname;
		this.mapattempt = mapattempt;
	}

	@Id
	@Column(name = "hostname", unique = true, nullable = false, length = 32)
	public String getHostname() {
		return this.hostname;
	}

	public void setHostname(String hostname) {
		this.hostname = hostname;
	}

	@Column(name = "mapattempt")
	public Long getMapattempt() {
		return this.mapattempt;
	}

	public void setMapattempt(Long mapattempt) {
		this.mapattempt = mapattempt;
	}

}
