package ict.ac.cn.hibernate;

// Generated 2014-8-24 12:59:22 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Jvm generated by hbm2java
 */
@Entity
@Table(name = "jvm", catalog = "bdtune")
public class Jvm implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4858614269090127846L;
	private Long jvmid;
	private String taskattemptId;
	private Double s0c;
	private Double s1c;
	private Double s0u;
	private Double s1u;
	private Double ec;
	private Double eu;
	private Double oc;
	private Double pc;
	private Double ou;
	private Double pu;
	private Double ygc;
	private Double ygct;
	private Double fgc;
	private Double fgct;
	private Double gct;
	private Long time;

	public Jvm() {
	}

	public Jvm(String taskattemptId, Double s0c, Double s1c, Double s0u,
			Double s1u, Double ec, Double eu, Double oc, Double pc, Double ou,
			Double pu, Double ygc, Double ygct, Double fgc, Double fgct,
			Double gct, Long time) {
		this.taskattemptId = taskattemptId;
		this.s0c = s0c;
		this.s1c = s1c;
		this.s0u = s0u;
		this.s1u = s1u;
		this.ec = ec;
		this.eu = eu;
		this.oc = oc;
		this.pc = pc;
		this.ou = ou;
		this.pu = pu;
		this.ygc = ygc;
		this.ygct = ygct;
		this.fgc = fgc;
		this.fgct = fgct;
		this.gct = gct;
		this.time = time;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "jvmid", unique = true, nullable = false)
	public Long getJvmid() {
		return this.jvmid;
	}

	public void setJvmid(Long jvmid) {
		this.jvmid = jvmid;
	}

	@Column(name = "taskattempt_id")
	public String getTaskattemptId() {
		return this.taskattemptId;
	}

	public void setTaskattemptId(String taskattemptId) {
		this.taskattemptId = taskattemptId;
	}

	@Column(name = "s0c", precision = 22, scale = 0)
	public Double getS0c() {
		return this.s0c;
	}

	public void setS0c(Double s0c) {
		this.s0c = s0c;
	}

	@Column(name = "s1c", precision = 22, scale = 0)
	public Double getS1c() {
		return this.s1c;
	}

	public void setS1c(Double s1c) {
		this.s1c = s1c;
	}

	@Column(name = "s0u", precision = 22, scale = 0)
	public Double getS0u() {
		return this.s0u;
	}

	public void setS0u(Double s0u) {
		this.s0u = s0u;
	}

	@Column(name = "s1u", precision = 22, scale = 0)
	public Double getS1u() {
		return this.s1u;
	}

	public void setS1u(Double s1u) {
		this.s1u = s1u;
	}

	@Column(name = "EC", precision = 22, scale = 0)
	public Double getEc() {
		return this.ec;
	}

	public void setEc(Double ec) {
		this.ec = ec;
	}

	@Column(name = "EU", precision = 22, scale = 0)
	public Double getEu() {
		return this.eu;
	}

	public void setEu(Double eu) {
		this.eu = eu;
	}

	@Column(name = "OC", precision = 22, scale = 0)
	public Double getOc() {
		return this.oc;
	}

	public void setOc(Double oc) {
		this.oc = oc;
	}

	@Column(name = "PC", precision = 22, scale = 0)
	public Double getPc() {
		return this.pc;
	}

	public void setPc(Double pc) {
		this.pc = pc;
	}

	@Column(name = "OU", precision = 22, scale = 0)
	public Double getOu() {
		return this.ou;
	}

	public void setOu(Double ou) {
		this.ou = ou;
	}

	@Column(name = "PU", precision = 22, scale = 0)
	public Double getPu() {
		return this.pu;
	}

	public void setPu(Double pu) {
		this.pu = pu;
	}

	@Column(name = "YGC", precision = 22, scale = 0)
	public Double getYgc() {
		return this.ygc;
	}

	public void setYgc(Double ygc) {
		this.ygc = ygc;
	}

	@Column(name = "YGCT", precision = 22, scale = 0)
	public Double getYgct() {
		return this.ygct;
	}

	public void setYgct(Double ygct) {
		this.ygct = ygct;
	}

	@Column(name = "FGC", precision = 22, scale = 0)
	public Double getFgc() {
		return this.fgc;
	}

	public void setFgc(Double fgc) {
		this.fgc = fgc;
	}

	@Column(name = "FGCT", precision = 22, scale = 0)
	public Double getFgct() {
		return this.fgct;
	}

	public void setFgct(Double fgct) {
		this.fgct = fgct;
	}

	@Column(name = "GCT", precision = 22, scale = 0)
	public Double getGct() {
		return this.gct;
	}

	public void setGct(Double gct) {
		this.gct = gct;
	}

	@Column(name = "time")
	public Long getTime() {
		return this.time;
	}

	public void setTime(Long time) {
		this.time = time;
	}

}
