package ict.ac.cn.hibernate;

// Generated 2014-8-24 12:59:22 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Meminfo generated by hbm2java
 */
@Entity
@Table(name = "meminfo", catalog = "bdtune")
public class Meminfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2876576077362403079L;
	private Long memid;
	private String hostname;
	private Long time;
	private Long memTotal;
	private Long free;
	private Long buffers;
	private Long cached;
	private Long swapCached;
	private Long active;
	private Long inactive;
	private Long swapTotal;
	private Long swapFree;

	public Meminfo() {
	}

	public Meminfo(String hostname) {
		this.hostname = hostname;
	}

	public Meminfo(String hostname, Long time, Long memTotal, Long free,
			Long buffers, Long cached, Long swapCached, Long active,
			Long inactive, Long swapTotal, Long swapFree) {
		this.hostname = hostname;
		this.time = time;
		this.memTotal = memTotal;
		this.free = free;
		this.buffers = buffers;
		this.cached = cached;
		this.swapCached = swapCached;
		this.active = active;
		this.inactive = inactive;
		this.swapTotal = swapTotal;
		this.swapFree = swapFree;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "memid", unique = true, nullable = false)
	public Long getMemid() {
		return this.memid;
	}

	public void setMemid(Long memid) {
		this.memid = memid;
	}

	@Column(name = "hostname", nullable = false, length = 32)
	public String getHostname() {
		return this.hostname;
	}

	public void setHostname(String hostname) {
		this.hostname = hostname;
	}

	@Column(name = "time")
	public Long getTime() {
		return this.time;
	}

	public void setTime(Long time) {
		this.time = time;
	}

	@Column(name = "mem_total")
	public Long getMemTotal() {
		return this.memTotal;
	}

	public void setMemTotal(Long memTotal) {
		this.memTotal = memTotal;
	}

	@Column(name = "free")
	public Long getFree() {
		return this.free;
	}

	public void setFree(Long free) {
		this.free = free;
	}

	@Column(name = "buffers")
	public Long getBuffers() {
		return this.buffers;
	}

	public void setBuffers(Long buffers) {
		this.buffers = buffers;
	}

	@Column(name = "cached")
	public Long getCached() {
		return this.cached;
	}

	public void setCached(Long cached) {
		this.cached = cached;
	}

	@Column(name = "swap_cached")
	public Long getSwapCached() {
		return this.swapCached;
	}

	public void setSwapCached(Long swapCached) {
		this.swapCached = swapCached;
	}

	@Column(name = "active")
	public Long getActive() {
		return this.active;
	}

	public void setActive(Long active) {
		this.active = active;
	}

	@Column(name = "inactive")
	public Long getInactive() {
		return this.inactive;
	}

	public void setInactive(Long inactive) {
		this.inactive = inactive;
	}

	@Column(name = "swap_total")
	public Long getSwapTotal() {
		return this.swapTotal;
	}

	public void setSwapTotal(Long swapTotal) {
		this.swapTotal = swapTotal;
	}

	@Column(name = "swap_free")
	public Long getSwapFree() {
		return this.swapFree;
	}

	public void setSwapFree(Long swapFree) {
		this.swapFree = swapFree;
	}

}
