package ict.ac.cn.hibernate;

// Generated 2014-8-24 12:59:22 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProcessCpu generated by hbm2java
 */
@Entity
@Table(name = "process_cpu", catalog = "bdtune")
public class ProcessCpu implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4624643093263659429L;
	private Long PCpuid;
	private String taskattemptId;
	private Long utime;
	private Long stime;
	private Long cutime;
	private Long cstime;
	private Long numThreads;
	private Long startTime;
	private Long time;

	public ProcessCpu() {
	}

	public ProcessCpu(String taskattemptId, Long utime, Long stime,
			Long cutime, Long cstime, Long numThreads, Long startTime, Long time) {
		this.taskattemptId = taskattemptId;
		this.utime = utime;
		this.stime = stime;
		this.cutime = cutime;
		this.cstime = cstime;
		this.numThreads = numThreads;
		this.startTime = startTime;
		this.time = time;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "p_cpuid", unique = true, nullable = false)
	public Long getPCpuid() {
		return this.PCpuid;
	}

	public void setPCpuid(Long PCpuid) {
		this.PCpuid = PCpuid;
	}

	@Column(name = "taskattempt_id")
	public String getTaskattemptId() {
		return this.taskattemptId;
	}

	public void setTaskattemptId(String taskattemptId) {
		this.taskattemptId = taskattemptId;
	}

	@Column(name = "utime")
	public Long getUtime() {
		return this.utime;
	}

	public void setUtime(Long utime) {
		this.utime = utime;
	}

	@Column(name = "stime")
	public Long getStime() {
		return this.stime;
	}

	public void setStime(Long stime) {
		this.stime = stime;
	}

	@Column(name = "cutime")
	public Long getCutime() {
		return this.cutime;
	}

	public void setCutime(Long cutime) {
		this.cutime = cutime;
	}

	@Column(name = "cstime")
	public Long getCstime() {
		return this.cstime;
	}

	public void setCstime(Long cstime) {
		this.cstime = cstime;
	}

	@Column(name = "num_threads")
	public Long getNumThreads() {
		return this.numThreads;
	}

	public void setNumThreads(Long numThreads) {
		this.numThreads = numThreads;
	}

	@Column(name = "start_time")
	public Long getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Long startTime) {
		this.startTime = startTime;
	}

	@Column(name = "time")
	public Long getTime() {
		return this.time;
	}

	public void setTime(Long time) {
		this.time = time;
	}

}
