package ict.ac.cn.hibernate;

// Generated 2014-8-24 12:59:22 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Snmp generated by hbm2java
 */
@Entity
@Table(name = "snmp", catalog = "bdtune")
public class Snmp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2625063308243138751L;
	private Long snmpid;
	private String hostname;
	private Long activeConn;
	private Long passiveConn;
	private Long rbytes;
	private Long rpackets;
	private Long rerrs;
	private Long rdrop;
	private Long sbytes;
	private Long spackets;
	private Long serrs;
	private Long sdrop;
	private Long time;

	public Snmp() {
	}

	public Snmp(String hostname) {
		this.hostname = hostname;
	}

	public Snmp(String hostname, Long activeConn, Long passiveConn,
			Long rbytes, Long rpackets, Long rerrs, Long rdrop, Long sbytes,
			Long spackets, Long serrs, Long sdrop, Long time) {
		this.hostname = hostname;
		this.activeConn = activeConn;
		this.passiveConn = passiveConn;
		this.rbytes = rbytes;
		this.rpackets = rpackets;
		this.rerrs = rerrs;
		this.rdrop = rdrop;
		this.sbytes = sbytes;
		this.spackets = spackets;
		this.serrs = serrs;
		this.sdrop = sdrop;
		this.time = time;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "snmpid", unique = true, nullable = false)
	public Long getSnmpid() {
		return this.snmpid;
	}

	public void setSnmpid(Long snmpid) {
		this.snmpid = snmpid;
	}

	@Column(name = "hostname", nullable = false, length = 32)
	public String getHostname() {
		return this.hostname;
	}

	public void setHostname(String hostname) {
		this.hostname = hostname;
	}

	@Column(name = "active_conn")
	public Long getActiveConn() {
		return this.activeConn;
	}

	public void setActiveConn(Long activeConn) {
		this.activeConn = activeConn;
	}

	@Column(name = "passive_conn")
	public Long getPassiveConn() {
		return this.passiveConn;
	}

	public void setPassiveConn(Long passiveConn) {
		this.passiveConn = passiveConn;
	}

	@Column(name = "rbytes")
	public Long getRbytes() {
		return this.rbytes;
	}

	public void setRbytes(Long rbytes) {
		this.rbytes = rbytes;
	}

	@Column(name = "rpackets")
	public Long getRpackets() {
		return this.rpackets;
	}

	public void setRpackets(Long rpackets) {
		this.rpackets = rpackets;
	}

	@Column(name = "rerrs")
	public Long getRerrs() {
		return this.rerrs;
	}

	public void setRerrs(Long rerrs) {
		this.rerrs = rerrs;
	}

	@Column(name = "rdrop")
	public Long getRdrop() {
		return this.rdrop;
	}

	public void setRdrop(Long rdrop) {
		this.rdrop = rdrop;
	}

	@Column(name = "sbytes")
	public Long getSbytes() {
		return this.sbytes;
	}

	public void setSbytes(Long sbytes) {
		this.sbytes = sbytes;
	}

	@Column(name = "spackets")
	public Long getSpackets() {
		return this.spackets;
	}

	public void setSpackets(Long spackets) {
		this.spackets = spackets;
	}

	@Column(name = "serrs")
	public Long getSerrs() {
		return this.serrs;
	}

	public void setSerrs(Long serrs) {
		this.serrs = serrs;
	}

	@Column(name = "sdrop")
	public Long getSdrop() {
		return this.sdrop;
	}

	public void setSdrop(Long sdrop) {
		this.sdrop = sdrop;
	}

	@Column(name = "time")
	public Long getTime() {
		return this.time;
	}

	public void setTime(Long time) {
		this.time = time;
	}

}
